/**
 * ISLAND mode's host half: the file + process work behind @app/core's
 * `IslandControl`. Thin sibling of `session-trace-reader.ts` / `git-worktree.ts`
 * — main owns the disk and the `open`/`defaults`/`osascript` shell-outs, the
 * renderer only marshals over `paneApi`.
 *
 * Main deliberately never touches CodeIsland's socket. The hook script (written
 * here, generated by core) pipes each hook's stdin straight into CodeIsland's
 * own bridge binary, so the wire protocol, the blocking read, and the process
 * ancestry that click-to-focus depends on all stay upstream's problem. That also
 * means no server of any kind is introduced in main.
 *
 * Every function swallows its own failures: a missing island must degrade to
 * "panes prompt in-pane as usual", never to a broken app.
 */
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import process from 'node:process';
import { execFile, execFileSync } from 'node:child_process';
import {
  buildGateFile,
  mergeCodeIslandHooks,
  renderIslandHookScript,
  splitCodeIslandHooks,
  CODEISLAND_BRIDGE_SUBPATH,
  CODEISLAND_BUNDLE_ID,
  CODEISLAND_CLAUDE_TOGGLE_KEY,
  type ClaudeHooksMap,
  type IslandStatus,
} from '@app/core';
import { resolveChorusHome } from '@app/store';

export interface IslandPaths {
  /** `<chorusHome>/island` — the mode's own corner of the profile tree. */
  dir: string;
  /** The allow-list of Claude session ids. Its existence IS the on switch. */
  gateFile: string;
  /** The script every island hook runs. */
  scriptPath: string;
  /** CodeIsland's client binary (installed by CodeIsland, never by us). */
  bridgePath: string;
}

/**
 * Honours CHORUS_HOME like the rest of the profile store, so a test or a second
 * instance pointed at another root gets its own gate instead of fighting over
 * `~/.chorus`.
 */
export function islandPaths(env: NodeJS.ProcessEnv = process.env): IslandPaths {
  const dir = path.join(resolveChorusHome(env), 'island');
  return {
    dir,
    gateFile: path.join(dir, 'enabled'),
    scriptPath: path.join(dir, 'hook.sh'),
    bridgePath: path.join(os.homedir(), CODEISLAND_BRIDGE_SUBPATH),
  };
}

/**
 * Write the hook script and return its path, or null if it could not be
 * written. Called once at startup, BEFORE the settings file is generated: the
 * hook entries are permanent and the gate file is what actually switches the
 * mode, so toggling never has to respawn a pane.
 */
export function installIslandScript(
  env: NodeJS.ProcessEnv = process.env,
): string | null {
  const p = islandPaths(env);
  try {
    fs.mkdirSync(p.dir, { recursive: true });
    fs.writeFileSync(
      p.scriptPath,
      renderIslandHookScript({
        gateFile: p.gateFile,
        bridgePath: p.bridgePath,
      }),
      { mode: 0o755 },
    );
    // writeFileSync's mode applies only on create; chmod covers a rewrite.
    fs.chmodSync(p.scriptPath, 0o755);
    return p.scriptPath;
  } catch {
    return null;
  }
}

/**
 * Run a command through a login shell. A GUI-launched Electron inherits a
 * minimal PATH, the same reason `session-catalog.ts` and the PTY spawn do this.
 * Resolves `{ ok, stdout }` — callers decide what a failure means.
 */
function sh(
  command: string,
  timeout = 10_000,
): Promise<{ ok: boolean; stdout: string }> {
  const shell = process.env.SHELL || '/bin/bash';
  return new Promise((resolve) => {
    execFile(
      shell,
      ['-l', '-c', command],
      { timeout, maxBuffer: 1024 * 1024 },
      (err, stdout) => resolve({ ok: !err, stdout: stdout ?? '' }),
    );
  });
}

/** Shell single-quote (paths may contain spaces). */
function q(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

async function exists(file: string): Promise<boolean> {
  try {
    await fsp.access(file);
    return true;
  } catch {
    return false;
  }
}

/** Does the bundle id resolve to an installed app? */
async function appFound(appPath?: string): Promise<boolean> {
  if (appPath && (await exists(appPath))) return true;
  const r = await sh(
    `osascript -e 'POSIX path of (path to application id "${CODEISLAND_BUNDLE_ID}")'`,
    8_000,
  );
  return r.ok && r.stdout.trim().length > 0;
}

/** CodeIsland's socket — present only while it is running and listening. */
function socketPath(): string {
  return (
    process.env.CODEISLAND_SOCKET_PATH ?? `/tmp/codeisland-${os.userInfo().uid}.sock`
  );
}

export async function probe(
  appPath?: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<IslandStatus> {
  const p = islandPaths(env);
  const [enabled, bridgeFound, socketFound, found] = await Promise.all([
    exists(p.gateFile),
    exists(p.bridgePath),
    exists(socketPath()),
    appFound(appPath),
  ]);
  return {
    enabled,
    appFound: found,
    bridgeFound,
    socketFound,
    ...(found
      ? bridgeFound
        ? {}
        : {
            error:
              'CodeIsland is installed but its bridge is missing — open CodeIsland once to install it.',
          }
      : { error: 'CodeIsland not found. Install it, or set its path below.' }),
  };
}

/**
 * Rewrite the allow-list. An empty list still writes the file (mode stays on,
 * nothing opted in) — deleting it is reserved for turning the mode off, which
 * is what `[ -f "$GATE" ]` in the script keys on.
 */
export async function writeGate(
  claudeSessionIds: string[],
  env: NodeJS.ProcessEnv = process.env,
): Promise<void> {
  const p = islandPaths(env);
  try {
    await fsp.mkdir(p.dir, { recursive: true });
    // Atomic: hooks read this file constantly, and a half-written gate would
    // silently drop panes for as long as the write took.
    const tmp = `${p.gateFile}.tmp`;
    await fsp.writeFile(tmp, buildGateFile(claudeSessionIds), 'utf8');
    await fsp.rename(tmp, p.gateFile);
  } catch {
    /* a gate we can't write means "nobody opted in" — never fatal */
  }
}

/**
 * Create the gate ONLY if it is missing.
 *
 * The gate's existence is the on-switch, so `setEnabled(true)` has to guarantee
 * the file is there — but it must never dictate the contents. The renderer owns
 * those: it is the only side that knows which panes are in the active
 * workspace. Writing an empty gate here unconditionally is a race, because on
 * startup the renderer fills the gate immediately while this path is still
 * awaiting several shell-outs (`defaults`, `osascript`, `open`) — so the empty
 * write lands last and silently un-enrols every pane. The mode then looks on,
 * badge and all, and no card ever appears.
 */
async function ensureGate(env: NodeJS.ProcessEnv): Promise<void> {
  const p = islandPaths(env);
  try {
    await fsp.mkdir(p.dir, { recursive: true });
    // `wx` fails when the file exists, which is exactly the no-op we want.
    await fsp.writeFile(p.gateFile, '', { flag: 'wx' });
  } catch {
    /* already there (the common case), or unwritable — both are fine */
  }
}

/** The user's own Claude Code settings — where CodeIsland installs its hooks. */
function claudeSettingsFile(): string {
  return path.join(os.homedir(), '.claude', 'settings.json');
}

/** Where we park CodeIsland's entries so turning the mode off can put them back. */
function hooksBackupFile(env: NodeJS.ProcessEnv): string {
  return path.join(islandPaths(env).dir, 'codeisland-hooks.backup.json');
}

/**
 * Flip CodeIsland's own Claude Code hook installer.
 *
 * Two separate things have to happen, and the second one is easy to miss:
 *
 *  1. `defaults write cli_enabled_claude false` stops CodeIsland's 60s
 *     auto-repair from re-adding its hooks behind our back.
 *  2. The entries ALREADY in `~/.claude/settings.json` must be removed. Inside
 *     CodeIsland that flag is written by a toggle whose other half calls
 *     `uninstallHooks`; there is no URL scheme or CLI to trigger that from
 *     outside, so writing the flag alone leaves every entry firing.
 *
 * Skipping (2) is not a cosmetic double-card bug. Claude Code waits for all
 * matching hooks, and CodeIsland's own PermissionRequest entry has an 86400s
 * timeout — one unanswered card would hold a pane for a day, which is exactly
 * the failure the bounded 60s design exists to prevent.
 *
 * Turning the mode off merges the saved entries back. CodeIsland's own
 * auto-repair is the backstop: with the flag true again it reinstalls them on
 * its next activation even if our restore never ran.
 */
async function setCodeIslandClaudeHooks(
  on: boolean,
  env: NodeJS.ProcessEnv,
): Promise<void> {
  await sh(
    `defaults write ${CODEISLAND_BUNDLE_ID} ${CODEISLAND_CLAUDE_TOGGLE_KEY} -bool ${on ? 'true' : 'false'}`,
  );
  const file = claudeSettingsFile();
  const backup = hooksBackupFile(env);
  try {
    const raw = await fsp.readFile(file, 'utf8');
    const settings = JSON.parse(raw) as { hooks?: ClaudeHooksMap };
    if (on) {
      const saved = JSON.parse(
        await fsp.readFile(backup, 'utf8').catch(() => '{}'),
      ) as ClaudeHooksMap;
      if (!Object.keys(saved).length) return;
      settings.hooks = mergeCodeIslandHooks(settings.hooks ?? {}, saved);
      await writeJsonAtomic(file, settings);
      await fsp.rm(backup, { force: true }).catch(() => {});
    } else {
      const { kept, removed } = splitCodeIslandHooks(settings.hooks ?? {});
      if (!Object.keys(removed).length) return; // already stripped
      // Save BEFORE mutating: a crash between the two must leave the user's
      // hooks recoverable, not lost.
      await fsp.mkdir(path.dirname(backup), { recursive: true });
      await writeJsonAtomic(backup, removed);
      settings.hooks = kept;
      await writeJsonAtomic(file, settings);
    }
  } catch {
    /* unreadable/absent settings: nothing to strip, nothing to restore */
  }
}

/** Write JSON via tmp+rename — `~/.claude/settings.json` is the user's file. */
async function writeJsonAtomic(file: string, value: unknown): Promise<void> {
  const tmp = `${file}.chorus.tmp`;
  await fsp.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
  await fsp.rename(tmp, file);
}

async function launch(appPath?: string): Promise<boolean> {
  const byId = await sh(`open -g -b ${CODEISLAND_BUNDLE_ID}`);
  if (byId.ok) return true;
  if (appPath) return (await sh(`open -g -a ${q(appPath)}`)).ok;
  return false;
}

async function quit(): Promise<void> {
  await sh(`osascript -e 'quit app id "${CODEISLAND_BUNDLE_ID}"'`);
}

/**
 * Synchronous teardown for `app.on('will-quit')`, which does not await
 * promises: drop the gate (every hook instantly goes back to `exit 0`) and hand
 * CodeIsland its own Claude hooks back. Both are state we changed on the user's
 * machine that would otherwise survive the process.
 */
export function restoreIslandOffState(
  _env: NodeJS.ProcessEnv = process.env,
): void {
  // The gate is deliberately LEFT in place. Chorus's panes die with Chorus, and
  // the hook script that reads the gate is referenced only by Chorus's own
  // generated settings file — so a gate that outlives the app cannot affect any
  // terminal. Deleting it, on the other hand, contradicts the persisted "on"
  // setting and makes every restart look broken until the startup reconcile
  // catches up. Handing CodeIsland's own hooks back is the part that matters:
  // that is real state we changed on the user's machine.
  try {
    execFileSync(
      '/usr/bin/defaults',
      ['write', CODEISLAND_BUNDLE_ID, CODEISLAND_CLAUDE_TOGGLE_KEY, '-bool', 'true'],
      { timeout: 2_000, stdio: 'ignore' },
    );
  } catch {
    /* CodeIsland may not be installed at all — nothing to restore */
  }
}

/**
 * Turn the mode on or off.
 *
 * On:  disable CodeIsland's own Claude hooks -> launch it -> create the gate.
 *      The gate is written LAST so no pane can block on an island that has not
 *      come up yet. It starts empty; the renderer immediately follows with the
 *      active workspace's panes.
 * Off: remove the gate FIRST (every hook instantly goes back to `exit 0`), then
 *      quit the app and restore its own hooks. Order matters in both
 *      directions — a pane must never be able to block on a dead island.
 */
export async function setEnabled(
  enabled: boolean,
  appPath?: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<IslandStatus> {
  const p = islandPaths(env);
  if (!enabled) {
    await fsp.rm(p.gateFile, { force: true }).catch(() => {});
    await quit();
    await setCodeIslandClaudeHooks(true, env);
    return probe(appPath, env);
  }

  const status = await probe(appPath, env);
  if (!status.appFound) return { ...status, enabled: false };

  await setCodeIslandClaudeHooks(false, env);
  const launched = await launch(appPath);
  if (!launched) {
    await setCodeIslandClaudeHooks(true, env);
    return {
      ...status,
      enabled: false,
      error: 'Could not launch CodeIsland.',
    };
  }
  // Make sure the script exists even if the startup write failed (e.g. the
  // profile dir was created after launch).
  installIslandScript(env);
  await ensureGate(env);
  return probe(appPath, env);
}
